print("Mark Christian M. Naling")
print("Santol, Boac, Marinduque")
print("March 04,2001")
print("Marinduque State College")
print("BSI/T -2A")
print("Chess")
print("Exercise")
print("Video Games")
print("Traveling")
print("Drawing")